# Generated by Django 3.2.8 on 2021-11-08 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_judul', models.CharField(max_length=100)),
                ('blog_isi', models.TextField()),
                ('blog_datetime', models.DateTimeField()),
                ('randomnumber', models.IntegerField(default=1000000)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GambarBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar_nama', models.CharField(max_length=100)),
                ('komentar_email', models.CharField(max_length=100)),
                ('komentar_isi', models.CharField(max_length=100)),
                ('komentar_datetime', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='gambars',
            field=models.ManyToManyField(blank=True, to='blog.GambarBlog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='kategoris',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.kategori'),
        ),
        migrations.AddField(
            model_name='blog',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
