# Generated by Django 3.2.8 on 2021-11-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentar',
            old_name='blog',
            new_name='blogs',
        ),
    ]
