# Generated by Django 3.2.8 on 2021-11-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_komentar_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambarblog',
            name='gambar',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
