# Generated by Django 3.2.8 on 2021-11-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_gambarblog_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='gambars',
        ),
        migrations.AddField(
            model_name='gambarblog',
            name='blogs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
        migrations.AddField(
            model_name='gambarblog',
            name='judul_gambar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gambarblog',
            name='gambar',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
