# Generated by Django 3.2.8 on 2021-11-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211130_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GambarBlog',
            new_name='Gambar',
        ),
    ]
