# Generated by Django 3.2.8 on 2021-11-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_gambarblog_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambar',
            name='blogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
