# Generated by Django 3.2.8 on 2022-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211130_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GambarBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Gambar',
        ),
        migrations.AddField(
            model_name='blog',
            name='gambars',
            field=models.ManyToManyField(blank=True, to='blog.GambarBlog'),
        ),
    ]
