# Generated by Django 3.2.8 on 2021-11-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smkmukti', '0002_alter_gallery_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gambar',
            field=models.ImageField(upload_to=''),
        ),
    ]
