# Generated by Django 3.2.8 on 2021-11-29 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smkmukti', '0003_alter_gallery_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='')),
                ('isi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FolderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(default='', upload_to='')),
                ('ket_gambar', models.CharField(blank=True, max_length=100)),
                ('agendas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smkmukti.agenda')),
                ('pengumumans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smkmukti.pengumuman')),
            ],
        ),
        migrations.CreateModel(
            name='KategoriJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='kurikulum',
            name='users',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='users',
        ),
        migrations.DeleteModel(
            name='DetailKurikulum',
        ),
        migrations.DeleteModel(
            name='Kurikulum',
        ),
        migrations.DeleteModel(
            name='Pendaftar',
        ),
        migrations.AddField(
            model_name='detailjurusan',
            name='kategorijurusans',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smkmukti.kategorijurusan'),
        ),
    ]
