# Generated by Django 3.2.8 on 2022-04-11 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smkmukti', '0004_auto_20211129_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailKurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('sub_judul', models.CharField(max_length=100)),
                ('isi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=15)),
                ('nama_ayah', models.CharField(max_length=100)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('tanggal_daftar', models.DateField()),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='folderimage',
            name='agendas',
        ),
        migrations.RemoveField(
            model_name='folderimage',
            name='pengumumans',
        ),
        migrations.RemoveField(
            model_name='kategorijurusan',
            name='users',
        ),
        migrations.DeleteModel(
            name='DetailJurusan',
        ),
        migrations.DeleteModel(
            name='FolderImage',
        ),
        migrations.DeleteModel(
            name='KategoriJurusan',
        ),
        migrations.AddField(
            model_name='detailkurikulum',
            name='kurikulums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smkmukti.kurikulum'),
        ),
    ]
